FROM docker.io/library/fedora:latest

RUN dnf install -y @development-tools util-linux git make curl wget tar xz gawk unzip \
    openssl-devel zlib-devel bzip2-devel readline-devel sqlite-devel libffi-devel \
    pkgconfig re2c bison autoconf libxml2-devel oniguruma-devel libcurl-devel \
    libzip-devel gettext-devel libicu-devel libpng-devel libjpeg-turbo-devel \
    freetype-devel gdbm-devel libwebp-devel libXpm-devel gcc-c++ automake libtool \
    harfbuzz-devel graphite2-devel fontconfig-devel gd-devel pcre2-devel \
    && dnf clean all

RUN useradd -m -s /bin/bash tester

# Command to build container image
# podman build -t my-amd64-fedora-tester -f Dockerfile.amd64_fedora
