[cargo]
stylua
git-delta
eza
zoxide
tectonic
bacon
cargo-watch

[npm]
yarn
tree-sitter-cli
markdown-toc
prettier
markdownlint-cli2
bash-language-server
basedpyright
typescript
typescript-language-server
@mermaid-js/mermaid-cli

[rustup]
rustfmt
clippy
rust-analyzer

[go]
mvdan.cc/sh/v3/cmd/shfmt@latest
github.com/jesseduffield/lazygit@latest
github.com/mikefarah/yq/v4@latest
mvdan.cc/sh/v3/cmd/shfmt@latest
golang.org/x/tools/gopls@latest
github.com/golangci/golangci-lint/cmd/golangci-lint@latest
