# ~/.bashrc.d/global_source.conf
# Global desired versions for user-space environments.
# If left blank, the manager will install the latest stable/LTS version 
# and automatically write the exact version number back to this file.

VERSION_NVM="22"
VERSION_JAVA="21.0.2-tem"
VERSION_RUBY="3.3.6"
VERSION_PHP="8.3.4"
VERSION_PYTHON="3.12"
